### ISSUE TITLE
Confusing plan behaviour

### ISSUE THREAD

**Issue by zanderhavgaard** [lunarway/shuttle#136]
Hello! I'm trying out shuttle, but experiencing some weird behavior when using a remote git plan:

My `shuttle.yaml` looks like this:
```
plan: git@github.com:<my-org>/<my-repo>
```

When I run `shuttle plan` I get the following output:
```
Error: exit code 2 - Failed to open plan configuration: open /home/zander/<my-org>/<my-repo>/git@github.com:<my-org>/<my-repo>/plan.yaml: no such file or directory

Make sure you are in a project using shuttle and that a 'shuttle.yaml' file is available.
Usage:
... (help-output) ...

shuttle failed
Failed to open plan configuration: open /home/zander/<my-org>/<my-repo>git@github.com:<my-org>/<my-repo>/plan.yaml: no such file or directory

Make sure you are in a project using shuttle and that a 'shuttle.yaml' file is available.
```

Which I would expect to work as per the readme.

--- 

If I change the plan to the `git://` syntax it works as expected:
```
# shuttle.yaml
plan: git://git@github.com:<my-org>/<my-repo>
```
```
# terminal
❯ shuttle plan
git://git@github.com:<my-org>/<my-repo>% 
```

Am I doing something wrong? Or is the documentation not correct?

---

PS. Shuttle looks cool, we are thinking about adopting it for our build needs, thanks for doing open-source! :smile:

**Comment by Crevil** [comment]
This seems like a bad case of documentation. We need the protocol in the URL to make the right decission on how to fetch the plan.

Are you up for contributing a PR with a fix?
