### ISSUE TITLE
OS X command for downloading throws error

### ISSUE THREAD

**Issue by Karnich** [lunarway/shuttle#36]
when trying to fire 
`curl -LO https://github.com/lunarway/shuttle/releases/download/$(curl -Lso /dev/null -w %{url_effective} https://github.com/lunarway/shuttle/releases/latest | grep -o '[^/]*$')/shuttle-darwin-amd64`

throws the following error:
`parse error near `)'`

**Comment by emilingerslev** [comment]
Interesting. I'll have to look into that 🤔
Can you supply what OS? (I guess some version of MacOS based on what you're trying to download)
What shell are you using and what version?
Thanks! 🙏

**Comment by Crevil** [comment]
I just verified the Mac OS script on macOS 10.14.3 and zsh 5.6.2 and had no issues.

**Comment by Karnich** [comment]
hmm i just tried it in the terminal instead of zsh. works fine there <.<

**Comment by Crevil** [comment]
I just verified with zsh `5.7.1` as well and it succeeds.

**Comment by Karnich** [comment]
when i copy paste :
```
curl -LO https://github.com/lunarway/shuttle/releases/download/$(curl -Lso /dev/null -w %{url_effective} https://github.com/lunarway/shuttle/releases/latest | grep -o '[^/]*$')/shuttle-darwin-amd64
```
but my console outputs:
```
curl -LO https://github.com/lunarway/shuttle/releases/download/$\(curl -Lso /dev/null -w %{url_effective} https://github.com/lunarway/shuttle/releases/latest | grep -o '[^/]*$')/shuttle-darwin-amd64
```

So something is wrong on my machine ;)  move along, nothing to see here
