### ISSUE TITLE
Validate that scripts has a least 1 action

### ISSUE THREAD

**Issue by emilingerslev** [lunarway/shuttle#4]
It does not make sense that scripts do not have actions, so fail running the script if so. Plus maybe consider a warning when doing an overall validation.

**Comment by emilingerslev** [comment]
Related to #3

**Comment by Crevil** [comment]
Related to #6 as well.

**Comment by kjuulh** [comment]
Because of the golang actions, this is actually a legal approach now. Which invalidates this issue
